default:
    pattern:  /
    defaults: { _controller: AppSiteBundle:Default:index }
homepage_lng:
    pattern:  /{lang}
    defaults: { _controller: AppSiteBundle:Default:index }
news:
    pattern:  /{lang}/news
    defaults: { _controller: AppSiteBundle:Default:newsList, lang: en }

contact_form:
    pattern:  /{lang}/contact
    defaults: { _controller: AppSiteBundle:Default:contact }

contact_form_send:
    pattern:  /{lang}/contact-send
    defaults: { _controller: AppSiteBundle:Default:contactSend }

page_news:
    pattern:  /{lang}/news/{kitCmsBlockSlug}
    defaults: { _controller: AppSiteBundle:Default:news, lang: en }

###
# purchase process
###

AppSiteBundle_shop_displayOrder:
    pattern: /shop/display-order/{orderId}
    defaults: { _controller: AppSiteBundle:PurchaseProcess:displayOrder }

AppSiteBundle_shop_identification:
    pattern:  /shop/identification
    defaults: { _controller: AppSiteBundle:PurchaseProcess:identification }

KitpagesShopCmsBundle_shop_cart:
    pattern:  /shop/cart
    defaults: { _controller: AppSiteBundle:PurchaseProcess:cart}

AppSiteBundle_shop_backShop:
    pattern:  /shop/back-to-shop
    defaults: { _controller: AppSiteBundle:PurchaseProcess:backToShop}

###
# user area
###

AppSiteBundle_userArea_orderList:
    pattern:  /userArea/orderList
    defaults: { _controller: AppSiteBundle:UserArea:orderList }

AppSiteBundle_userArea_orderDisplay:
    pattern:  /userArea/orderDisplay/{orderId}
    defaults: { _controller: AppSiteBundle:UserArea }

###
# catalog
###
AppSiteBundle_catalog_category:
    pattern:  /catalog/category/{categoryName}
    defaults: { _controller: AppSiteBundle:Catalog:category }